owner: etriphany
repo: uptime-monitor

sites:
  - name: Etriphany
    url: http://www.etriphany.com
  - name: GreenKeeper API
    url: https://green-keeper-vercel.vercel.app

status-website:
  baseUrl: /uptime-monitor
  theme: night
  name: Uptime Monitor
  introTitle: "Uptime monitor and status page for Etriphany"
  navbar:
    - title: Status
      href: /
    - title: Etriphany
      href: http://www.etriphany.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"