owner: etriphany
repo: uptime-monitor
sites:
  - name: Etriphany
    url: https://www.etriphany.com
  - name: GreenKeeper API
    url: https://green-keeper-vercel.vercel.app
status-website:
  baseUrl: / uptime-monitor
  theme: light

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"