owner: etriphany-com
repo: uptime-monitor

sites:
  - name: Etriphany
    url: http://www.etriphany.com
    type: globalping
    location: aws+europe,aws+north america,aws+south america --limit 2
  - name: GreenKeeper API
    url: https://green-keeper-vercel.vercel.app/health
    type: globalping
    location: aws+europe,aws+north america,aws+south america --limit 2

status-website:
  cname: status.etriphany.com
  theme: night
  name: Uptime Monitor
  introTitle: "Etriphany's uptime monitors"
  navbar:
    - title: Status
      href: /
    - title: Etriphany
      href: http://www.etriphany.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *"